name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches: [ main, feature/*, dev ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pages: write
      id-token: write
    
    concurrency:
      group: "pages"
      cancel-in-progress: false
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.27.1'
        channel: 'stable'
        cache: true
    
    - name: Clean Flutter
      run: flutter clean
    
    - name: Get dependencies
      run: flutter pub get
    
    - name: Run build_runner
      run: flutter packages pub run build_runner build --delete-conflicting-outputs
    
    - name: Build Flutter Web
      run: flutter build web --release --base-href "/avocado-pwa/" --verbose
    
    - name: Setup Pages
      uses: actions/configure-pages@v4
    
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: build/web
    
    - name: Deploy to GitHub Pages
      id: deployment
      if: github.ref == 'refs/heads/main'
      uses: actions/deploy-pages@v4